config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get 'auth/:provider/callback' => 'sessions#omniauth' 

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'
 
  get '/search' => 'restaurants#search'
  

  resources :reviews
  resources :restaurants do
     resources :reviews
  end 
  resources :users
     resources :restaurants, only: [:index] do
     end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :category #, optional: true
    belongs_to :user 
    has_many :reviews, :dependent => :destroy
    has_many :users, through: :reviews
    
   
    validates :image, presence: true
    validates :city, presence: true
    validates :country, presence: true
    validates :website, presence: true


    mount_uploader :image, ImageUploader

    def self.category
        c = where(:category_id => @category_id).order("created_at DESC")
    end 

    def average_review
        if self.reviews.blank?
            @average_review = 0
           else
            @average_review = self.reviews.average(:rating).round(1)
           end 
    end 
    
    def number_of_reviews
        @number_of_reviews = self.reviews.count 
    end 

end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :user
  belongs_to :restaurant

  validates :rating, presence: true
  validates :date, presence: true
  validates :comment, presence: true

 
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :restaurants, through: :reviews 
   

    has_secure_password 

    validates :password, length: {in: 8..100}, confirmation: true
    validates :username, uniqueness: true, length: {in: 5..30}
    validates :email, presence: true, uniqueness: true, format: {with: /\A(?<username>[^@\s]+)@((?<domain_name>[-a-z0-9]+)\.(?<domain>[a-z]{2,}))\z/i}
 

    def self.from_omniauth(auth)   
    self.find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |u|
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(20)
            u.username = auth['info']['name'].downcase.gsub(" ", "_")
        end 
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
   
    helper_method :current_user, :logged_in?


    private 
    def current_user
        @current_user ||=User.find_by_id(session[:user_id]) if session[:user_id]
    end 

    def logged_in?
        !!session[:user_id]
    end 

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end 
    

end 

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    before_action :redirect_if_not_logged_in
    before_action :find_restaurant, only: [:show, :edit, :update, :destroy]


    def index
        if params[:category].blank?
          @restaurants = Restaurant.all
        else
         @category_id = Category.find_by(name: params[:category]).id
         @restaurants = Restaurant.category
    end 
 end 

 def search
    @restaurants = Restaurant.where("name LIKE ?", "%" + params[:q] + "%")  
    render :index
 end 

    def show  
      
    end 

    def new
        @restaurant = Restaurant.new
        @categories = Category.all.map{|c| [c.name, c.id] }
    end  


    def create    
      @restaurant = current_user.restaurants.build(restaurant_params)
      @restaurant.user = current_user
      @restaurant.category_id = params[:category_id]
    if @restaurant.save
        redirect_to restaurants_path
    else
        render :new
    end 
end 


def edit
   @categories = Category.all.map{|c| [c.name, c.id] }
end 

def update
    @restaurant.category_id = params[:category_id]
    if @restaurant.update(restaurant_params)
     redirect_to restaurant_path(@restaurant)
    else
    render :edit
  end 
end 

def destroy
    @restaurant.destroy
    redirect_to '/'
 end 


 

private
    def restaurant_params 
       
        params.require(:restaurant).permit(:name, :image, :city, :country, :website, :category_id)
    end 



def find_restaurant
    @restaurant = Restaurant.find_by(id: params[:id])
end 

end 

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   
   before_action :find_restaurant
   before_action :find_review, only: [:edit, :update, :destroy]
   
    def new
     @review = Review.new
    end
    
    def index
      if params[:restaurant_id] && @restaurant = Restaurant.find_by_id(params[:restaurant_id])
        @reviews = @restaurant.reviews
    else
      @reviews = Review.all
    end 
  end 

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    current_user.reviews << @review
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end 
  end 

  def edit
  end 

  def update
    if @review.update(review_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
  end 
end 

def destroy
  @review.destroy
  redirect_to restaurant_path(@restaurant)
end 


    private
    def review_params
        params.require(:review).permit(:date, :rating, :comment, :category, :image)
    end 

    def find_restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
    end 

    def find_review
      @review = Review.find(params[:id])
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def welcome 
  end 

  def new
  end 

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
    redirect_to user_path(@user)
    else
      flash[:error] = "Sorry, login info is incorrect, please try again."
      redirect_to login_path
  end 
end

def omniauth
  @user = User.from_omniauth(auth)
if @user.valid?
  session[:user_id] = @user.id
  redirect_to @user
else
  render :new
end 
end 

  def destroy
    session.clear
    redirect_to '/'
  end 
end

private 

 def auth
   request.env['omniauth.auth']
 end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
end 

def index
end 

def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  else 
    render :new
end 
end  

def show
    redirect_if_not_logged_in
    @user = User.find_by(id: params[:id])
    redirect_to '/' if !@user
end 


private 

def user_params
    params.require(:user).permit(:username, :email, :password)
end 

  end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>ResRev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<script src="https://code.jquery.com/jquery-2.2.4.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<nav class="navbar navbar-default">
      <div class="container">
       <div class="navbar-header">
        <%= link_to "Restaurant Review", restaurants_path, class: "navbar-brand" %>
       </div>

       <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
            <li class="<%= 'active' if params[:category] == category.name %>">
            <%= link_to category.name, restaurants_path(category: category.name), class: "link" %>
            </li>
            <% end %>
          </ul>
        </li>
       <% if logged_in? %>
       <li><%= link_to "Add a Restaurant", new_restaurant_path %></li>
       <li><%= link_to "Your Added Restaurant", user_path(current_user) %></li>
       <li><%= link_to "Log Out", logout_path, method: :delete %></li>
       <% else %>
       <li><%= link_to "Signup", signup_path %></li>
       <li><%= link_to "Login", login_path %></li>
       <% end %>
       </ul>
       <br>
       <form class="form-inline my-2 my-lg-0 navbar-right"action="/search">
       <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
     </form>
      </div>
      </nav>
     
  </head>

  <body>
   
     <div class="container">
    <%= yield %>
    </div>

  </body>

  <br><br><br>

     <footer class="branding">
        <small>&copy; 2021 <strong>ResRev</strong></small>
      </footer>
</html>

app/views/owners/new.html.erb
<h1>Sign up</h1>

<%= form_for (@owner) do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :Email %>
    <%= f.email_field :email %>
    <br>
    <%= f.label :Password %>
    <%= f.password_field :password %>
    <br>
    <%= f.submit "Sign Up" %>

<% end %>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @restaurant.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for (@restaurant) do |f| %>

    <%= f.label :category %>
    <%= select_tag(:category_id, options_from_collection_for_select(Category.all, :id, :name), include_blank: "Select Category") %><br>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    
    <div class="form-group">
    <%= f.file_field :image %>
    </div>
  
    <%= f.label :City %>
    <%= f.text_field :city %>
    <br>

    <%= f.label :Country %>
    <%= f.text_field :country %>
    <br>

    <%= f.label :Website %>
    <%= f.text_field :website %>
    <br>

    <%= f.submit "Submit" %>


   

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<body>
<% if flash[:error] %>
<div class="errors flash fatal">
   <h3 class="error"><%= flash[:error] %>
   </div>
   <% end %>

<h3>All Restaurants</h3>

<% if @restaurants.count == 0 %>
 <h4>The Restaurant you want to review is not in the category:- </h4>
      <h4>please <%= link_to "Add a Restaurant", new_restaurant_path %> and review </h4>
<% else %>

<div class="row">
  <% @restaurants.each do |restaurant| %>

    <% if restaurant.try(:image).try(:url)%>
    <div class="col-md-3">
      <%= restaurant.name %><br>
      <%= link_to image_tag(restaurant.image.url, :size => "250x250"), restaurant_path(restaurant) %> 
    </div>
  <% end %>
<% end %>

  </div>
<% end %>
</body>

app/views/restaurants/new.html.erb
<h1>Add a New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/search.html.erb
<h1>Search Results</h1>
<%= render @restaurants %>

app/views/restaurants/show.html.erb
<body>
<% if flash[:error] %>
<div class="errors flash fatal">
   <h3 class="error"><%= flash[:error] %>
   </div>
   <% end %>

<h4>Restaurant added by:- <%= @restaurant.user.username %></h4>


<div class="row">

 <% if @restaurant.try(:image).try(:url)%>
  <div class="col-md-4">
    <%= image_tag @restaurant.image.url, :size => "375x325" %>
  </div>

  <div class="col-md-8">
  <h2><%= @restaurant.name %><h2>
      <h4>Average Rating:- <%= @restaurant.average_review %></h4>

   <%= @restaurant.city %><br>
   <%= @restaurant.country %><br>
   <%= link_to @restaurant.website, "http://#{@restaurant.website}", target: "_blank" %><br>
   <h4><%= @restaurant.number_of_reviews %> Reviews | <%= link_to "See All Reviews", restaurant_reviews_path(@restaurant) %> </h4>
   <h4><%= link_to "Add a New Review", new_restaurant_review_path(@restaurant) %></h4>

</div>
</div>



<%= link_to "Back", './' %> |

<% if logged_in? %>
<% if @restaurant.user_id == current_user.id %>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %> |
<%= link_to "Delete", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
<% end %>
<% end %>
</body>

app/views/reviews/_form.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @review.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([@restaurant, @review]) do |f| %>
    
    <%= f.label :rating %>
    <%= f.select :rating, options_for_select([1,2,3,4,5]), include_blank: "select rating" %>
    <br>

    <%= f.label :date %>
    <%= f.text_field :date, :placeholder => 'mm/dd/yyyy' %>
    <br>

    <%= f.label :category %>
    <%= f.select :category, [ 'Breakfast', 'Brunch', 'Lunch', 'Afternoon tea', 'Dinner' ], :prompt => 'Select One' %>
    <br>

    <%= f.label :comment %>
    <%= f.text_field :comment %>
    <br>
 
    <div class="form-group">
    <%= f.file_field :image %>
    </div>
   
    <%= f.submit "Submit" %>

    <% end %>

app/views/reviews/_review.html.erb
<p>Rating: <%= review.rating %></p>
<p>Review_date:<%= review.date %></p>
<p>Meal: <%= review.category %></p>
<p>Comment: <%= review.comment %></p>
<p>Image: <br>
    <img src="<%= review.image.url %>" width=150px height=100px > </p>

    
    
<% if logged_in? %>
<% if review.user_id == current_user.id %>
<%= link_to "Edit", edit_restaurant_review_path(review.restaurant, review) %>
<%= link_to "Delete", restaurant_review_path(review.restaurant, review), method: :delete, data: {confirm: "are you sure?"} %>
<% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

 <%= render 'form' %>

  

app/views/reviews/index.html.erb
<body>
<% if flash[:error] %>
<div class="errors flash fatal">
   <h3 class="error"><%= flash[:error] %>
   </div>
   <% end %>

<h1>All Reviews</h1>
<h2><%= @restaurant.name %></h2>
<% @restaurant.reviews.each do |review| %>
    <li><%= review.user.username %> <br>
    <%= render review %>
<% end %>
<br>
        <%= link_to "Back", restaurant_path(@restaurant) %> |

     </body>

app/views/reviews/new.html.erb
<h1>Add Review</h1>
 <%= render 'form' %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do |message|%>
    <div class="field_with_errors">
     <h3><%= message %> </h3>
   </div>
<%end%>
<%end%>

<h1>Sign up</h1>

<%= form_for (@user) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
   
    <%= f.label :Email %>
    <%= f.email_field :email %>
    <br>
    <%= f.label :Password %>
    <%= f.password_field :password %>
    <br>
    <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
<% if flash[:error] %>
<div class="errors flash fatal">
   <h3 class="error"><%= flash[:error] %>
   </div>
   <% end %>

Welcome <%= @user.username %> <br><br>

<% if @user.restaurants.present? %>

</h3>here are the restaurant/s you recently added. <br><h3>

   <% @user.restaurants.each do |r| %>
    <% if r.try(:image).try(:url)%>
    <div class="col-md-4">
    <br>
    <%= link_to image_tag(r.image.url, :size => "350x300"), restaurant_path(r) %>
  </div>
  
  <% end %>
  <% end %>
  <% end %>
  
    